### ISSUE TITLE
Error (spawn ENOENT) in Visual Studio Code

### ISSUE THREAD

**Issue by rofrano** [jan-dolejsi/vscode-pddl#57] opened 2020-03-16 14:32 UTC
After installing The **PDDL** extension into Visual Studio Code 1.43.0, on my Mac (macOS 10.14.6) when I open a `pddl` file I get the following error:
```
spawn "/Users/rofrano/Library/Application Support/Code/User/globalStorage/jan-dolejsi.pddl/val/Val-20190911.1-Darwin/bin/Parser" ENOENT
```

It then prompts me to:
```
Setup a PDDL parser or download VAL Tools in order to enable detailed syntactic analysis.
```
which I have already done several times.

When I looked in: `~/Library/Application Support/Code/User/globalStorage/jan-dolejsi.pddl/val/Val-20190911.1-Darwin/bin` the files have no execute bit set?

This is what I see:
```
-rw-rw-rw-  1 rofrano  staff    46K Sep 11  2019 Analyse
-rw-rw-rw-  1 rofrano  staff    53K Sep 11  2019 DomainView
-rw-rw-rw-  1 rofrano  staff    13K Sep 11  2019 HowWhatWhen
-rw-rw-rw-  1 rofrano  staff    16K Sep 11  2019 Instantiate
-rw-rw-rw-  1 rofrano  staff    29K Sep 11  2019 Parser
...
```

I changed them with `chmod 755` so they look like this:
```
-rwxr-xr-x  1 rofrano  staff    46K Sep 11  2019 Analyse*
-rwxr-xr-x  1 rofrano  staff    53K Sep 11  2019 DomainView*
-rwxr-xr-x  1 rofrano  staff    13K Sep 11  2019 HowWhatWhen*
-rwxr-xr-x  1 rofrano  staff    16K Sep 11  2019 Instantiate*
-rwxr-xr-x  1 rofrano  staff    29K Sep 11  2019 Parser*
...
```

but I continue to get the same error. What am I doing wrong or is this a bug?

**Comment by CallumWatkins** [comment] 2020-04-14 17:38
I'm getting the same error on Windows 10 1909 build 18363.752, VS Code 1.44.1.

**Comment by jan-dolejsi** [comment] 2020-04-29 09:01
Thanks and apology for the inconvenience. On Linux the extension used to prompt the user to chmod manually (as a form of consent). But since about 3 weeks ago, I `chmod` the 4 executables that VS Code is using (Parser, Validate, ValStep, ValueSeq) automatically. I do not have a Mac computer to test, but this automated test is passing on Linux, Mac and Windows:

```typescript
        it("changed chmod", async () => {
            const manifest = await readValManifest(VAL_MANIFEST);
            expect(manifest.valStepPath, "valstep should be present").to.not.be.undefined;
            if (manifest.valStepPath) {
                fs.accessSync(path.join(VAL_DIRECTORY_ABS, manifest.valStepPath), fs.constants.X_OK);
            }
        });
```

Let me know if that is the case - if you force re-download of the VAL binaries, they shall be executable now.

But since you manually flipped the executable bit (and @CallumWatkins  has a similar issue on Windows), can you confirm what do you see when you run the parser from the command line? Just give it your domain.pddl file as the only argument first.

**Comment by tranhoangkhuongvn** [comment] 2020-05-01 07:01
I have just installed the tool on Mac 10.15.4 and got the exact same issue. I tried to change the execution permission on the Parser but it does not help.

**Comment by jan-dolejsi** [comment] 2020-05-01 15:41
Can you run the `Parser` tool from command-line on your PDDL domain and let me know if it runs ok (prints out a syntax tree), or shows an error?

The parser has a simple interface:

```bash
Parser domain.pddl [problem.pddl]
```

**Comment by CallumWatkins** [comment] 2020-05-01 16:52
@jan-dolejsi I am able to run the Parser from the command line directly with correct output (with and without the problem file).

**Comment by tranhoangkhuongvn** [comment] 2020-05-02 00:56
> Can you run the `Parser` tool from command-line on your PDDL domain and let me know if it runs ok (prints out a syntax tree), or shows an error?
> 
> The parser has a simple interface:
> 
> ```shell
> Parser domain.pddl [problem.pddl]
> ```

Hi, I cannot run the Parser on the command line: `zsh: command not found: Parser`.
I just installed the plugging directly from VSCode without any other changes to system configuration. Please advise me how to do this.

Thanks

**Comment by jan-dolejsi** [comment] 2020-05-04 08:24
Ok, no problem. Here is what I would like you to try:

1. Open the PDDL Overview Page
1. Assuming you downloaded the VAL binaries per the prompt, you will find the absolute Parser path one of the input fields. If you triple-click onto the input field, the full path should select; copy it to clip-board
1. In the VS Code File Explorer, right click on your domain file and select "Open in Terminal"
1. Paste the absolute Parser path to the terminal window, add the domain file name as the only argument to the Parser and press Enter

This should call the Parser from where it got installed on your computer. I am interested in the output you get.

**Comment by tranhoangkhuongvn** [comment] 2020-05-04 09:58
Hi, I think my problem lies in the way the MacOS folder was named:
- Originally, there is a space in the folder "Application Support"
`/Users/myname/Library/Application Support/Code/User/globalStorage/jan-dolejsi.pddl/val/Val-20190911.1-Darwin/bin/Parser domain_1.pddl`
I tried to add in "\" and it works as normal
`/Users/khuongtran/Library/Application\ Support/Code/User/globalStorage/jan-dolejsi.pddl/val/Val-20190911.1-Darwin/bin/Parser domain_1.pddl `

**Comment by jan-dolejsi** [comment] 2020-05-04 12:10
Great. Thanks. That is interesting. I will re-visit the code that calls the planner and ensure it can run from locations with spaces.

If you added double quotes around the whole path in the VS Code configuration setting, the extension shall no longer be prompting you to configure the parser. There must be another failure in the spawning of the external process. But first, let me have a look at the automatic insertion of the `\` or double-quoting. 

The configuration setting `pddlParser.executableOrService` is not interpreted as an executable path, because it could actually be something like `java -jar pddl4j.jar`.

**Comment by jan-dolejsi** [comment] 2020-05-07 12:12
I am pushing a change that escapes the spaces in VAL paths by `\` on MacOS. To test it I modified the integration test to have a space in the emulated global storage path. I would really appreciate if you re-test and let me know:

1.  If you re-download VAL binaries now and elect to overwrite previous configuration, does it escape the space in the configuration entry `pddlParser.executableOrService`?
1. Does parsing now work, when you edit a PDDL domain file?

Besides the build machine, I do not have access to a MacOS : (

**Comment by jan-dolejsi** [comment] 2020-05-07 12:14
Manually re-opening the issue closed by the Pull Request, because I need the confirmation from someone with a Mac computer.

**Comment by tranhoangkhuongvn** [comment] 2020-05-07 12:25
Hi,
I've just reinstalled the plugin and the issue is still there. There is still a pop up menu whenever I edit the .pddl file:
`Setup a PDDL parser or download VAL tools in order to enable detailed syntactic analysis`
and
`spawn "/Users/myname/Library/Application Supprt/Code/User/globalStorage/jan-dolejsi.pddl/val/Val-20190911.1-Darwin/bin/Parser" ENOENT`

**Comment by jan-dolejsi** [comment] 2020-05-10 13:38
Thanks. And can you confirm that you re-triggered the VAL binary download and accepted the previous configuration to be over-written?

**Comment by tranhoangkhuongvn** [comment] 2020-05-11 01:18
Hi, yes I've tried 2 approaches: over-written and removed the plug-in and re-installed it again.

**Comment by rofrano** [comment] 2020-05-15 16:03
@jan-dolejsi Sorry I didn't get back to you sooner. 

Thanks for the update. I removed the plug-in and deleted the folder it was installed in, and reinstalled the plug-in and I can confirm that the executables now have their execute bits set properly as you can see:

```bash
$ ls -l jan-dolejsi.pddl/val/Val-20190911.1-Darwin/bin/
total 4952
-rw-rw-rw-  1 rofrano  staff    46K Sep 11  2019 Analyse
-rw-rw-rw-  1 rofrano  staff    53K Sep 11  2019 DomainView
-rw-rw-rw-  1 rofrano  staff    13K Sep 11  2019 HowWhatWhen
-rw-rw-rw-  1 rofrano  staff    16K Sep 11  2019 Instantiate
---xr-----  1 rofrano  staff    29K Sep 11  2019 Parser*
-rw-rw-rw-  1 rofrano  staff    31K Sep 11  2019 PinguPlan
-rw-rw-rw-  1 rofrano  staff   112K Sep 11  2019 PlanRec
-rw-rw-rw-  1 rofrano  staff    68K Sep 11  2019 PlanSeqStep
-rw-rw-rw-  1 rofrano  staff    40K Sep 11  2019 PlanToValStep
-rw-rw-rw-  1 rofrano  staff    32K Sep 11  2019 Relax
-rw-rw-rw-  1 rofrano  staff    14K Sep 11  2019 TIM
-rw-rw-rw-  1 rofrano  staff    16K Sep 11  2019 ToFn
-rw-rw-rw-  1 rofrano  staff    82K Sep 11  2019 TypeAnalysis
---xr-----  1 rofrano  staff    67K Sep 11  2019 ValStep*
---xr-----  1 rofrano  staff    94K Sep 11  2019 Validate*
---xr-----  1 rofrano  staff    50K Sep 11  2019 ValueSeq*
-rw-rw-rw-  1 rofrano  staff   1.6M Sep 11  2019 libVAL.dylib
```

When I invoke the `Parser` from the command line that works.

Back in VSCode, when I right-click on a `problem.pddl` file and select **PDDL: Run the planner and display the plan** the plan does get displayed in another window so the planner seems to be working. 

While it is working, I still get this error in a popup window in the lower right after running the plan:
```
spawn "/Users/rofrano/Library/Application Support/Code/User/globalStorage/jan-dolejsi.pddl/val/Val-20190911.1-Darwin/bin/Parser" ENOENT
```

I also have the same issue as @tranhoangkhuongvn in that every time I open VSCode and then select my `domain.pddl` file it prompts me to install VAL Tools again:

```
Setup a [PDDL parser](https://github.com/jan-dolejsi/vscode-pddl/wiki/Configuring-the-PDDL-parser "Read more about PDDL parsers") or download [VAL Tools](https://github.com/KCL-Planning/VAL) in order to enable detailed syntactic analysis.
```

Not sure why it doesn't know that VAL Tools is installed?

**Comment by felixvd** [comment] 2020-07-09 13:18
I can confirm the above for macOS 10.14.6. I also get both the prompt to download VAL Tools and the `spawn [...]/Parser ENOENT` error.

**Comment by shmulvad** [comment] 2020-08-28 17:04
I can confirm that I still get the above mentioned error (I am running macOS 10.15.6 and VS Code 1.48.2). I tried to add a `\` before the space in `"Application Support"`, but this didn't help fix my issue either.

What seemed to work was copying the binaries from the downloaded VAL to a new path that contained no spaces and then referencing this absolute path in the settings. So now I have the binaries stored at `~/VAL/bin/` and reference `~/VAL/bin/Parser` etc.

This is of course not optimal, but for anyone on macOS who just wants the issue fixed for now, this should do it.

**Comment by jan-dolejsi** [comment] 2020-11-05 09:45
@shmulvad @felixvd @rofrano all, can you please retry again (with VAL placed in the default download location, see whether you get syntax validation reported by the Parser)?

I removed all of my attempts to handle the space in the VAL path and node.js `process.spawn` should just do the right thing.

Thx

**Comment by jan-dolejsi** [comment] 2021-01-13 13:10
I did not hear back, so I am hoping things are working on Mac. If anyone still has an issue having the VAL utilities working on Mac, submit an issue.

**Closed by jan-dolejsi** 2021-01-13 13:10 UTC
